### ISSUE TITLE
implicit imports

### ISSUE THREAD

**Issue by dgketchum** [DRI-WSWUP/pyWeatherQAQC#1]
Great package!

for readability please use explicit imports:

`from foo import bar `

is better than

`from foo import *`

because later in the code we see

`bar.do_something()` 
rather than `do_something` which is good because a new user reading your code knows where 

`do_something()` came from

**Comment by cwdunkerly** [comment]
Thank you for the suggestion. All imports are now either explicit or name the package the function came from.
