### ISSUE TITLE
Latitude Units

### ISSUE THREAD

**Issue by ba-minor** [DRI-WSWUP/pyWeatherQAQC#2]
Inputting latitude units as decimal degrees raises ValueError:

![lat_units](https://user-images.githubusercontent.com/30845152/45900721-61008180-bd95-11e8-9959-74153b3ec058.PNG)

I am using refet version 0.3.7 and I used a station latitude in decimal degrees in the .ini file.
refet version 0.3.7 is supposed to expect decimal degrees but I am being warned that latitudes must be in radians.

**Comment by ba-minor** [comment]
Update 9/24/18:

This issue arises when you are using refet 0.3.1. I misidentified my version at first glance.

**Comment by cwdunkerly** [comment]
My apologies for not responding to this sooner, for some reason I did not get any notification when you opened your issue. 

I am in the middle of a complete rewrite of my script to make it more condensed and efficient, I will add handling to indicate if the refet package is the wrong version. I appreciate the feedback and please let me know if you have any other suggestions and issues.
