### ISSUE TITLE
Add 2m Short Grass Windspeed column to output .csv 

### ISSUE THREAD

**Issue by cpearson1** [DRI-WSWUP/pyWeatherQAQC#3]
Call station windspeed column: "Windspeed_uz_{} (m/s)".format(anemometer_height)

Add 2m logarithmic correction wind speed column using ASCE eq. 33 (short grass)
"Windspeed_u2_sg (m/s)"

![image](https://user-images.githubusercontent.com/14983120/46173488-3ada5600-c25b-11e8-95e8-43de638ee785.png)

**Comment by cwdunkerly** [comment]
Sorry I did not respond to this sooner, for some reason I did not get a notification when you opened this issue. I will add this to the next version I am working on.

**Comment by cpearson1** [comment]
Hey Chris - Can you add this 2m windspeed to this version of PyWeatherQAQC? 

We are doing more development on the bias correction code and need that output column in your Corrected_Output_Data files.

**Comment by cwdunkerly** [comment]
2m windspeed is now output into a separate column of the output file on the development branch. I have more features to add and cleanup to do before I merge it with the master branch but what you want is all there. Let me know if it doesn't work for you.
