### ISSUE TITLE
ini input "lines_of_footer" doesn't skip final line(s) of met data

### ISSUE THREAD

**Issue by mattyrb** [DRI-WSWUP/pyWeatherQAQC#4]
Not very important, but Agrimet data ends with an 'END DATA' row.  I attempted to increase 'lines_of_footer' in the ini, but it didn't seem to skip that final line. It's easy to delete that row of data in excel, but it appears to be a feature that was wanted.

**Comment by cwdunkerly** [comment]
I have tested this with a few data files and it seems to be working as intended. Would you mind sending me the data file so that I can test it myself?
